### ISSUE TITLE
BINPUT8.DLL

### ISSUE THREAD

**Issue by fadster** [RollinBarrel/binary-domaim#3]
I'd like to give this a try but I was wondering why the filename changed from DINPUT8.DLL to BINPUT8.DLL in the latest version. Is it just a typo?

**Comment by RollinBarrel** [comment]
It was a typo, yes 😅
Thanks for the heads up!
I'm also not sure if i've uploaded the correct .dll (i think **B**INPUT one was a debug one), so please redownload it (https://github.com/RollinBarrel/binary-domaim/releases/download/v0.91/DINPUT8.dll)

**Comment by fadster** [comment]
Alright, it's working! I gave it a quick try and it seemed to make things better. I'll have to try it over a longer session. Thanks!
